name: Ultimate ImGui Android Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Download Gradle 8.3
        run: |
          wget https://services.gradle.org/distributions/gradle-8.3-bin.zip
          unzip -q gradle-8.3-bin.zip

      - name: Generate Wrapper with Gradle 8.3
        run: ./gradle-8.3/bin/gradle wrapper --gradle-version 8.3 --distribution-type bin

      - name: Remove local.properties
        run: rm -f local.properties

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
